### ISSUE TITLE
setting currentTime - performance issues

### ISSUE THREAD

**Issue by marcusand** [chrisguttandin/media-sync#2]
Hey, 

nice work, really like the library!
Currently playing around with it, trying to sync up two html5 based video players in local network. One issue, though. Seems like setting currentTime on the media elements sucks up performance pretty bad to a point where the video will go totally black for several seconds. 
From your description I assumed that syncing up time is done by adjusting playbackRate but looking in the code it seems like as soon as time has drifted currentTime is set. Correct?

Do you see a possible solution for saving performance? Do you think just adjusting playbackRate would work better?

**Comment by chrisguttandin** [comment]
Gude @marcusand,

the behavior should be different depending on which browser you are using. There is no way to adjust the playbackRate in Safari which leaves setting currentTime as the only option in Safari. Maybe that has changed. I think I did not check this lately.

In Chrome and Firefox the algorithm should adjust the playbackRate. At least until the offset is below the tolerance of 25ms.

Does that help?

**Comment by marcusand** [comment]
Gude :) Thanks for the answer.

maybe I am seeing something wrong, but to me it seems that here   https://github.com/chrisguttandin/timingsrc/blob/25c74dfcc530bc6bf8cb1316e0c938944ebca60f/src/factories/set-timingsrc-with-custom-update-function.ts#L24
currentTime is always set during playback. or is it not? 

I am commented that line out for testing and it did bring back the performance but videos, of course, were running out of syng again.

**Comment by marcusand** [comment]
ok, I think it's a bug and I found a possible solution:
https://github.com/marcusand/timingsrc/commit/551efc9e8b9e16342d807fd2cede691f4fccd6a4

Problem is that in `updateGradually` you are setting `position: currentTime` when adjusting the velocity. And then in the animationFrame function setting `playbackRate` is inside the if statement `if(currentTime !== position)` so it is never reaching the block. 

what do you think?

**Comment by marcusand** [comment]
if you want I can make that a PR

**Comment by chrisguttandin** [comment]
Oh, thanks for catching that. I think you're right, there is an error in the update logic. However, I'm not sure if your fix would work for all edge cases.

Let's say I'm playing a video at twice the speed (velocity = 2). Then I skip 2 seconds ahead. The skip would have no effect since the first if clause does still apply.

https://github.com/marcusand/timingsrc/commit/551efc9e8b9e16342d807fd2cede691f4fccd6a4#diff-a80a8d4dcb40bb14458f19b82a15acb3acd503a8179b97b4688fbef01f9dc301R14

This is super tricky to get right. I'll try to add a few tests for different scenarios. Hopefully that will allow us to fix bugs and handle edge cases without breaking any of the previously handled cases.

**Comment by marcusand** [comment]
Yeah I recognized that too now...not as easy as I thought :D 
but hey I could verify now, that adjusting playbackRate works so much better for my use case than jumping in the video. In that regard I think it would be super handy if one could set the threshold when setting up, instead of hardcoded. 

and to leave some props: I am quite amazed by your implementation of the timing object specification. Together with provider and server it works quite well. Keep it up :)

**Comment by chrisguttandin** [comment]
I think I added a test (and a fix) for each possible scenario. Could you please double check if it works for you now? Since this is all very complex there is a good chance I missed something.

Thanks again for making me aware of this problem.

Do you mind adding another issue for making the threshold configurable?

**Comment by marcusand** [comment]
Nice! 
At first glance it seems to work, but I'll do some in depth testing next week.
Thanks for fixing!
